version: '3.8'

services:
  spotify-auth-proxy:
    image: ghcr.io/conradludgate/spotify-auth-proxy
    env_file: .env
    ports:
      - "27228:27228"
    restart: always

  terraform-runner:
    # Build from the Dockerfile
    build: .
    depends_on:
      - spotify-auth-proxy
    environment:
      - SPOTIFY_AUTH_PROXY=http://spotify-auth-proxy:27228
    restart: always